# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='usergoal',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='activity_id',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='goal_id',
        ),
        migrations.AddField(
            model_name='user',
            name='activities',
            field=models.ManyToManyField(to='app.Activity'),
        ),
        migrations.AddField(
            model_name='user',
            name='goals',
            field=models.ManyToManyField(to='app.Goal'),
        ),
        migrations.DeleteModel(
            name='UserActivity',
        ),
        migrations.DeleteModel(
            name='UserGoal',
        ),
    ]
