# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 03:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_user_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Profile',
        ),
        migrations.AlterField(
            model_name='usermatch',
            name='user_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_match_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usermatch',
            name='user_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_match_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
