# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 03:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20171024_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2017, 10, 26, 3, 1, 15, 947013, tzinfo=utc)),
        ),
    ]
