# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 07:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20171026_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2017, 10, 26, 7, 43, 56, 998850, tzinfo=utc)),
        ),
    ]
