# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 08:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0028_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='users',
        ),
        migrations.RemoveField(
            model_name='usermatch',
            name='user_from',
        ),
        migrations.RemoveField(
            model_name='usermatch',
            name='user_to',
        ),
        migrations.AddField(
            model_name='usermatch',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
