# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 22:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_usermatch_current_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='goals',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='goal',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='usermatch',
            name='current_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_list_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
    ]
